### ISSUE TITLE
Run on Parabola GNU/Linux

### ISSUE THREAD

**Issue by theova** [lovac42/CCBC#14]
Hello,
I am trying to run CCBC on Parabola GNU/Linux ( a free ArchLinux derivative).
I installed the requirements with:
```
sudo pacman -S python-beautifulsoup4 python-send2trash python-pyaudio python-requests python-decorator python-markdown
```
Then tried to `./runanki`:
```Traceback (most recent call last):
  File "./runanki", line 3, in <module>
    import aqt
  File "/home/user/CCBC/aqt/__init__.py", line 16, in <module>
    from aqt.qt import *
  File "/home/user/CCBC/aqt/qt.py", line 10, in <module>
    import sip
ModuleNotFoundError: No module named 'sip'
```
So I installed `python-sip`.
After this, `pyqt4` was still missing:
```
Traceback (most recent call last):
  File "./runanki", line 3, in <module>
    import aqt
  File "/home/user/CCBC/aqt/__init__.py", line 16, in <module>
    from aqt.qt import *
  File "/home/user/CCBC/aqt/qt.py", line 13, in <module>
    from anki.utils import isWin, isMac
  File "/home/user/CCBC/anki/__init__.py", line 14, in <module>
    from anki.storage import Collection
  File "/home/user/CCBC/anki/storage.py", line 13, in <module>
    from ccbc.collection import _ExtCollection
  File "/home/user/CCBC/ccbc/collection.py", line 19, in <module>
    from ccbc.media import ExtMediaManager
  File "/home/user/CCBC/ccbc/media.py", line 19, in <module>
    from ccbc.utils import isURL, isDataURL
  File "/home/user/CCBC/ccbc/utils.py", line 10, in <module>
    from PyQt4 import QtCore, QtGui
ModuleNotFoundError: No module named 'PyQt4'
```
Parabola/Arch provides [https://www.parabola.nu/packages/community/x86_64/python-qtpy/](python-qtpy) which "Provides an uniform layer to support PyQt5, PyQt4 and PySide with a single codebase".

Installing it, did not help.

Parabola/Arch currently support pyqt5, I think the support for pyqt5 is dropped. Is there any way for me to get CCBC running? Or are there any plans to update to pyqt5?

Thanks alot!

**Comment by lovac42** [comment]
Webkit has been removed from pyqt5 and replaced with WebEngine. So you would need to install pyqt4 with qtWebkit. I compiled and install it manually from source for Debian and Slackware, but I don't know too much about linux flavors. If your distro still comes with it, such as Fedora, that would make things a lot easier.
